### ISSUE TITLE
Am I Missing Something

### ISSUE THREAD

**Issue by moshemo** [goldhat/acf-post-types#1]
I activated the plugin and clicked on Add New.  I'm taken to a page where with a title field and a wysiwyg editor.  No options to add a new custom post type.  Any ideas?

**Comment by goldhat** [comment]
Do you see "Post Types" in the admin menu? After clicking Add New you should see an ACF field (key) and then a tab for labels. See screenshot below. If you don't see those, it sounds like the ACF field group was not included. Not sure why that would happen (it's embedded). But check your ACF version? This is built for current ACF 5.3.7 and I have not tested on earlier... it should work on any ACF5 though, but might fail on ACF4.

![acf-post-types-add-post](https://cloud.githubusercontent.com/assets/2975282/15208762/0ea135b2-1836-11e6-8489-70b50cc4335b.png)

**Comment by moshemo** [comment]
I just switched to ACF Pro and now it is working.  Previously I had used the version that comes from the Wordpress repository (which I just downloaded). 

Thanks for the help.

**Comment by goldhat** [comment]
Glad it's working! Thanks for pointing out the issue... I think it should
work with ACF (free) because we're not using anything from the pro
version... so will have to test that some more.

On Thu, May 12, 2016 at 2:34 PM, moshemo <notifications@github.com> wrote:

> I just switched to ACF Pro and now it is working. Previously I had used
> the version that comes from the Wordpress repository (which I just
> downloaded).
>
> Thanks for the help.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/goldhat/acf-post-types/issues/1#issuecomment-218731721>
>



-- 
Best Regards,

Joel Milne, Project Manager
*GoldHat Marketing Group*

WEBSITE: www.GoldHat.ca <http://www.goldhat.ca/>
EMAIL: joel@goldhat.ca <contact@goldhat.ca>
PHONE: 1 (716) 402-4270

*CMS site development in WordPress and Drupal. WordPress plugin development
experts. Connect with us on Twitter at @GoldHatMG
<https://twitter.com/GoldHatMG>*
